// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhBZ-32ks7rsC0PLxX5oM1i3d9-Wl3QE8',
    appId: '1:870791278185:web:656624aa53a922cded7cf8',
    messagingSenderId: '870791278185',
    projectId: 'devcamp-firebase-126d1',
    authDomain: 'devcamp-firebase-126d1.firebaseapp.com',
    storageBucket: 'devcamp-firebase-126d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmqqPlUDuYcXPyockRQ6SR_cgX9yGAA5c',
    appId: '1:870791278185:android:81ed794e9f8540aded7cf8',
    messagingSenderId: '870791278185',
    projectId: 'devcamp-firebase-126d1',
    storageBucket: 'devcamp-firebase-126d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk40Mj5pD_wZz42lIcCiUbHM_pLrx2M64',
    appId: '1:870791278185:ios:e48b675ece11c81ced7cf8',
    messagingSenderId: '870791278185',
    projectId: 'devcamp-firebase-126d1',
    storageBucket: 'devcamp-firebase-126d1.appspot.com',
    iosBundleId: 'com.example.devcampFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk40Mj5pD_wZz42lIcCiUbHM_pLrx2M64',
    appId: '1:870791278185:ios:e48b675ece11c81ced7cf8',
    messagingSenderId: '870791278185',
    projectId: 'devcamp-firebase-126d1',
    storageBucket: 'devcamp-firebase-126d1.appspot.com',
    iosBundleId: 'com.example.devcampFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhBZ-32ks7rsC0PLxX5oM1i3d9-Wl3QE8',
    appId: '1:870791278185:web:77031286d5f52991ed7cf8',
    messagingSenderId: '870791278185',
    projectId: 'devcamp-firebase-126d1',
    authDomain: 'devcamp-firebase-126d1.firebaseapp.com',
    storageBucket: 'devcamp-firebase-126d1.appspot.com',
  );
}
